INSERT INTO company(name) VALUES ('WestJet');
INSERT INTO company(name) VALUES ('Vueling Airlines');
INSERT INTO company(name) VALUES ('Virgin Blue Airlines');
INSERT INTO company(name) VALUES ('Vietnam Airlines');
INSERT INTO company(name) VALUES ('US Airways');
INSERT INTO company(name) VALUES ('United Airlines');
INSERT INTO company(name) VALUES ('Turkish Airlines');
INSERT INTO company(name) VALUES ('Thomson Airways');
INSERT INTO company(name) VALUES ('Thai Airways International');
INSERT INTO company(name) VALUES ('TAM Linhas Aereas');
INSERT INTO company(name) VALUES ('Swiss');
INSERT INTO company(name) VALUES ('Southwest Airlines');
INSERT INTO company(name) VALUES ('SkyWest Airlines');
INSERT INTO company(name) VALUES ('Singapore Airlines');
INSERT INTO company(name) VALUES ('Shenzhen Airlines');
INSERT INTO company(name) VALUES ('Saudi Arabian Airlines');
INSERT INTO company(name) VALUES ('SAS Scandinavian Airlines');
INSERT INTO company(name) VALUES ('Ryanair');
INSERT INTO company(name) VALUES ('Qatar Airways');
INSERT INTO company(name) VALUES ('Qantas');
INSERT INTO company(name) VALUES ('Pinnacle Airlines');
INSERT INTO company(name) VALUES ('Norwegian Air Shuttle');
INSERT INTO company(name) VALUES ('trading as Norwegian');
INSERT INTO company(name) VALUES ('North America');
INSERT INTO company(name) VALUES ('Mesa Airlines');
INSERT INTO company(name) VALUES ('Malaysia Airlines');
INSERT INTO company(name) VALUES ('Lufthansa');
INSERT INTO company(name) VALUES ('Lion Air');
INSERT INTO company(name) VALUES ('Latin America/ Caribbean');
INSERT INTO company(name) VALUES ('LAN Airlines');
INSERT INTO company(name) VALUES ('Korean Air');
INSERT INTO company(name) VALUES ('Kingfisher Airlines');
INSERT INTO company(name) VALUES ('Jetstar');
INSERT INTO company(name) VALUES ('JetBlue Airways');
INSERT INTO company(name) VALUES ('Jet Airways');
INSERT INTO company(name) VALUES ('JAL Group(Japan Airlines)');
INSERT INTO company(name) VALUES ('Iberia Group');
INSERT INTO company(name) VALUES ('Hainan Group');
INSERT INTO company(name) VALUES ('Gol Linhas Aereas');
INSERT INTO company(name) VALUES ('Garuda Indonesia');
INSERT INTO company(name) VALUES ('Frontier Airlines');
INSERT INTO company(name) VALUES ('ExpressJet Airlines');
INSERT INTO company(name) VALUES ('Europe');
INSERT INTO company(name) VALUES ('Emirates Airline');
INSERT INTO company(name) VALUES ('easyJet');
INSERT INTO company(name) VALUES ('Delta Air Lines');
INSERT INTO company(name) VALUES ('Continental Airlines');
INSERT INTO company(name) VALUES ('China Southern Airlines');
INSERT INTO company(name) VALUES ('China Eastern Airlines');
INSERT INTO company(name) VALUES ('China Airlines');
INSERT INTO company(name) VALUES ('Cebu Pacific Air');
INSERT INTO company(name) VALUES ('Cathay Pacific');
INSERT INTO company(name) VALUES ('British Airways');
INSERT INTO company(name) VALUES ('AviancaTaca');
INSERT INTO company(name) VALUES ('Avianca');
INSERT INTO company(name) VALUES ('Austrian Airlines Group');
INSERT INTO company(name) VALUES ('Atlantic Southeast Airlines');
INSERT INTO company(name) VALUES ('Asiana Airlines');
INSERT INTO company(name) VALUES ('Asia/Pacific');
INSERT INTO company(name) VALUES ('American Eagle ');
INSERT INTO company(name) VALUES ('Alitalia');
INSERT INTO company(name) VALUES ('Alaska Airlines');
INSERT INTO company(name) VALUES ('AirTran Airways');
INSERT INTO company(name) VALUES ('AirAsia');
INSERT INTO company(name) VALUES ('Air New Zealand Group');
INSERT INTO company(name) VALUES ('Air France');
INSERT INTO company(name) VALUES ('Air China');
INSERT INTO company(name) VALUES ('Air Canada');
INSERT INTO company(name) VALUES ('Air Berlin Group');
INSERT INTO company(name) VALUES ('Africa/Middle East');
INSERT INTO company(name) VALUES ('Aeroflot Russian Airlines');
INSERT INTO company(name) VALUES ('Aer Lingus');
